version: 2

sources:
    - name: staging
      database: utility-logic-375619
      schema: trips_data_all_us

      tables:
        - name: green_tripdata_partitoned_clustered
        - name: yellow_tripdata_partitoned_clustered
        
