version: 2

sources:
    - name: staging
      database: utility-logic-375619
      schema: trips_data_all

      tables:
        -name: green_tripdata
        -name: yellow_tripdata
        